codepkg/objects/Departament__c.object
<CustomObject>
    <fields>
        <fullName>Offices__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Office</label>
        <referenceTo>Office__c</referenceTo>
        <relationshipLabel>Departments</relationshipLabel>
        <relationshipName>Departments</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Department</label>
    <nameField>
        <label>Departament Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Departments</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

codepkg/classes/TestDepartament.cls
public class TestDepartament {
        public static Departament__c createDepartament(String name, Id officeid) {
        Departament__c departament = new Departament__c(
            Name = name,
            Offices__c = officeId
        );
        
        Database.SaveResult sv = Database.insert(departament);
        return departament; 
}
    
    public static Boolean deleteDepartament (Id departamentID) {
        try {
       delete new Departament__c(Id = departamentID);
        }
        catch(Exception ex) {
            return false;
        }
        return true;
    }
    public static Departament__c updateDepartament(Id departamentID, String name) {
        Departament__c departament = new Departament__c(
            Id = departamentId,
            Name = name
            
        );
        
        Database.SaveResult sv = Database.update(departament);
        return departament; 
     }
}